---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de productos de StorageGRID
    url: "/index.html"
